version: '3'

services:
  database:
    container_name: mysql
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vitor
      MYSQL_PASSWORD: root
    volumes:
      - /var/lib/mysql
